site_name: "NCOR Riverside"
repo_url: https://github.com/NCOR-Organization/NCOR-Riverside/
site_description: NCOR Riverside
site_author: John Beverley / Cristian Keroles
edit_uri: '?query=root/NCOR-Organization/NCOR-Riverside/'

theme:
  name: material
  logo: assets/ncor-logo.png
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  hide:
    - toc

extra_css:
  - stylesheets/extra.css
  
nav:
  - About: index.md
  
